import { boolean, integer, jsonb, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const fixedCostSettings = pgTable("fixed_cost_settings", {
  id: text("id").primaryKey(),
  electricityMonthly: integer("electricity_monthly").notNull().default(0),
  waterMonthly: integer("water_monthly").notNull().default(0),
  internetMonthly: integer("internet_monthly").notNull().default(0),
  rentMonthly: integer("rent_monthly").notNull().default(0),
  doctorSalary: integer("doctor_salary").notNull().default(0),
  therapistSalary: integer("therapist_salary").notNull().default(0),
  beauticianSalary: integer("beautician_salary").notNull().default(0),
  adminSalary: integer("admin_salary").notNull().default(0),
  bpjsAllowance: integer("bpjs_allowance").notNull().default(0),
  cleaningLaundry: integer("cleaning_laundry").notNull().default(0),
  machineMaintenance: integer("machine_maintenance").notNull().default(0),
  marketing: integer("marketing").notNull().default(0),
  softwareSubscription: integer("software_subscription").notNull().default(0),
  equipmentInstallment: integer("equipment_installment").notNull().default(0),
  renovationInstallment: integer("renovation_installment").notNull().default(0),
  otherInstallment: integer("other_installment").notNull().default(0),
  otherFixedCost: integer("other_fixed_cost").notNull().default(0),
  workingDaysPerMonth: integer("working_days_per_month").notNull().default(26),
  operatingHoursPerDay: integer("operating_hours_per_day").notNull().default(9),
  averageCustomersPerMonth: integer("average_customers_per_month").notNull().default(1),
  costModes: jsonb("cost_modes").notNull().default({}),
  costNotes: jsonb("cost_notes").notNull().default({}),
  staffCosts: jsonb("staff_costs").notNull().default([]),
  electricitySettings: jsonb("electricity_settings").notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const treatments = pgTable("treatments", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  category: text("category").notNull().default(""),
  durationMinutes: integer("duration_minutes").notNull().default(0),
  defaultNonVipPrice: integer("default_non_vip_price").notNull().default(0),
  defaultVipPrice: integer("default_vip_price").notNull().default(0),
  promoPrice: integer("promo_price").notNull().default(0),
  targetMarginPercent: integer("target_margin_percent").notNull().default(40),
  staffInvolved: jsonb("staff_involved").notNull().default([]),
  disposableItems: jsonb("disposable_items").notNull().default([]),
  consumableUsages: jsonb("consumable_usages").notNull().default([]),
  materialItems: jsonb("material_items").notNull().default([]),
  machineItems: jsonb("machine_items").notNull().default([]),
  deviceElectricityCosts: jsonb("device_electricity_costs").notNull().default([]),
  shotCartridgeCosts: jsonb("shot_cartridge_costs").notNull().default([]),
  staffFeeCosts: jsonb("staff_fee_costs").notNull().default([]),
  includeOverhead: boolean("include_overhead").notNull().default(true),
  commissionRules: jsonb("commission_rules").notNull().default([]),
  heraCommissionRules: jsonb("hera_commission_rules").notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const products = pgTable("products", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  category: text("category").notNull().default(""),
  supplier: text("supplier").notNull().default(""),
  buyingTiers: jsonb("buying_tiers").notNull().default([]),
  normalPrice: integer("normal_price").notNull().default(0),
  vipPrice: integer("vip_price").notNull().default(0),
  promoPrice: integer("promo_price").notNull().default(0),
  stockQuantity: integer("stock_quantity"),
  commissionRules: jsonb("commission_rules").notNull().default([]),
  heraCommissionRules: jsonb("hera_commission_rules").notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const simulationRecords = pgTable("simulation_records", {
  id: text("id").primaryKey(),
  itemType: text("item_type").notNull(),
  itemId: text("item_id").notNull(),
  itemName: text("item_name").notNull(),
  customerType: text("customer_type").notNull(),
  sellingPrice: integer("selling_price").notNull().default(0),
  quantity: integer("quantity").notNull().default(1),
  directHpp: integer("direct_hpp").notNull().default(0),
  overheadCost: integer("overhead_cost").notNull().default(0),
  totalCost: integer("total_cost").notNull().default(0),
  grossProfit: integer("gross_profit").notNull().default(0),
  totalCommission: integer("total_commission").notNull().default(0),
  netProfit: integer("net_profit").notNull().default(0),
  marginPercent: integer("margin_percent").notNull().default(0),
  commissionBreakdown: jsonb("commission_breakdown").notNull().default([]),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const commissionLogs = pgTable("commission_logs", {
  id: text("id").primaryKey(),
  date: text("date").notNull(),
  customerName: text("customer_name").notNull(),
  itemType: text("item_type").notNull(),
  itemId: text("item_id"),
  itemName: text("item_name").notNull(),
  customerType: text("customer_type").notNull(),
  sellingPrice: integer("selling_price").notNull().default(0),
  quantity: integer("quantity").notNull().default(1),
  staffName: text("staff_name").notNull().default(""),
  staffRole: text("staff_role").notNull().default("admin"),
  commissionAmount: integer("commission_amount").notNull().default(0),
  totalSales: integer("total_sales").notNull().default(0),
  totalHpp: integer("total_hpp").notNull().default(0),
  netProfit: integer("net_profit").notNull().default(0),
  paymentStatus: text("payment_status").notNull().default("unpaid"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const consumableItems = pgTable("consumable_items", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  category: text("category").notNull().default("Other"),
  supplier: text("supplier"),
  purchasePrice: integer("purchase_price").notNull().default(0),
  purchaseQuantity: integer("purchase_quantity").notNull().default(1),
  purchaseUnit: text("purchase_unit").notNull().default("pack"),
  totalSmallestUnit: integer("total_smallest_unit").notNull().default(0),
  smallestUnit: text("smallest_unit").notNull().default("pcs"),
  costPerSmallestUnit: integer("cost_per_smallest_unit").notNull().default(0),
  availableQuantity: integer("available_quantity").notNull().default(0),
  minimumStock: integer("minimum_stock").notNull().default(0),
  currentStock: integer("current_stock").notNull().default(0),
  stockUnit: text("stock_unit").notNull().default("pcs"),
  lastStockCheckDate: text("last_stock_check_date"),
  lastStockCheckBy: text("last_stock_check_by"),
  lastPhysicalStock: integer("last_physical_stock"),
  lastStockDifference: integer("last_stock_difference"),
  notes: text("notes"),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const stockAdjustments = pgTable("hpp_stock_adjustments", {
  id: text("id").primaryKey(),
  materialId: text("material_id").notNull(),
  materialNameSnapshot: text("material_name_snapshot").notNull(),
  type: text("type").notNull(),
  quantity: integer("quantity").notNull().default(0),
  previousStock: integer("previous_stock").notNull().default(0),
  newStock: integer("new_stock").notNull().default(0),
  reason: text("reason").notNull(),
  notes: text("notes"),
  date: text("date").notNull(),
  pic: text("pic").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const stockOpnames = pgTable("hpp_stock_opnames", {
  id: text("id").primaryKey(),
  date: text("date").notNull(),
  checkedBy: text("checked_by").notNull().default(""),
  location: text("location"),
  notes: text("notes"),
  status: text("status").notNull().default("draft"),
  items: jsonb("items").notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const staffDirectory = pgTable("hpp_staff_directory", {
  id: text("id").primaryKey(),
  staffCode: text("staff_code").notNull(),
  name: text("name").notNull(),
  role: text("role").notNull(),
  status: text("status").notNull().default("active"),
  phone: text("phone"),
  notes: text("notes"),
  defaultCommissionEligible: boolean("default_commission_eligible").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const staffRoles = pgTable("hpp_staff_roles", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const commissionDrafts = pgTable("hpp_commission_drafts", {
  id: text("id").primaryKey(),
  transactionDate: text("transaction_date").notNull(),
  invoiceNumber: text("invoice_number").notNull(),
  patientName: text("patient_name"),
  itemName: text("item_name").notNull(),
  treatmentId: text("treatment_id"),
  staffId: text("staff_id"),
  staffNameSnapshot: text("staff_name_snapshot").notNull(),
  role: text("role").notNull(),
  commissionMode: text("commission_mode").notNull(),
  baseAmount: integer("base_amount").notNull().default(0),
  normalPrice: integer("normal_price").notNull().default(0),
  finalAllocatedAmount: integer("final_allocated_amount").notNull().default(0),
  percent: integer("percent").notNull().default(0),
  nominal: integer("nominal").notNull().default(0),
  calculatedCommission: integer("calculated_commission").notNull().default(0),
  hppCost: integer("hpp_cost").notNull().default(0),
  estimatedProfit: integer("estimated_profit").notNull().default(0),
  status: text("status").notNull().default("draft"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const commissionHistory = pgTable("hpp_commission_history", {
  id: text("id").primaryKey(),
  transactionDate: text("transaction_date").notNull(),
  invoiceNumber: text("invoice_number").notNull(),
  patientName: text("patient_name"),
  itemName: text("item_name").notNull(),
  treatmentId: text("treatment_id"),
  staffId: text("staff_id"),
  staffNameSnapshot: text("staff_name_snapshot").notNull(),
  role: text("role").notNull(),
  commissionMode: text("commission_mode").notNull(),
  baseAmount: integer("base_amount").notNull().default(0),
  normalPrice: integer("normal_price").notNull().default(0),
  finalAllocatedAmount: integer("final_allocated_amount").notNull().default(0),
  percent: integer("percent").notNull().default(0),
  nominal: integer("nominal").notNull().default(0),
  calculatedCommission: integer("calculated_commission").notNull().default(0),
  hppCost: integer("hpp_cost").notNull().default(0),
  estimatedProfit: integer("estimated_profit").notNull().default(0),
  status: text("status").notNull().default("approved"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const commissionRules = pgTable("hpp_commission_rules", {
  id: text("id").primaryKey(),
  itemType: text("item_type").notNull(),
  itemId: text("item_id").notNull(),
  rules: jsonb("rules").notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const hppPackageTemplates = pgTable("hpp_package_templates", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  category: text("category").notNull().default("Other"),
  description: text("description"),
  items: jsonb("items").notNull().default([]),
  totalCost: integer("total_cost").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const hppCategories = pgTable("hpp_categories", {
  id: text("id").primaryKey(),
  group: text("group").notNull(),
  name: text("name").notNull(),
  active: boolean("active").notNull().default(true),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
