import { integer, jsonb, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const fixedCostSettings = pgTable("fixed_cost_settings", {
  id: text("id").primaryKey(),
  electricityMonthly: integer("electricity_monthly").notNull().default(0),
  waterMonthly: integer("water_monthly").notNull().default(0),
  internetMonthly: integer("internet_monthly").notNull().default(0),
  rentMonthly: integer("rent_monthly").notNull().default(0),
  doctorSalary: integer("doctor_salary").notNull().default(0),
  therapistSalary: integer("therapist_salary").notNull().default(0),
  beauticianSalary: integer("beautician_salary").notNull().default(0),
  adminSalary: integer("admin_salary").notNull().default(0),
  bpjsAllowance: integer("bpjs_allowance").notNull().default(0),
  cleaningLaundry: integer("cleaning_laundry").notNull().default(0),
  machineMaintenance: integer("machine_maintenance").notNull().default(0),
  marketing: integer("marketing").notNull().default(0),
  softwareSubscription: integer("software_subscription").notNull().default(0),
  equipmentInstallment: integer("equipment_installment").notNull().default(0),
  renovationInstallment: integer("renovation_installment").notNull().default(0),
  otherInstallment: integer("other_installment").notNull().default(0),
  otherFixedCost: integer("other_fixed_cost").notNull().default(0),
  workingDaysPerMonth: integer("working_days_per_month").notNull().default(26),
  operatingHoursPerDay: integer("operating_hours_per_day").notNull().default(9),
  averageCustomersPerMonth: integer("average_customers_per_month").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const treatments = pgTable("treatments", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  category: text("category").notNull().default(""),
  durationMinutes: integer("duration_minutes").notNull().default(0),
  defaultNonVipPrice: integer("default_non_vip_price").notNull().default(0),
  defaultVipPrice: integer("default_vip_price").notNull().default(0),
  promoPrice: integer("promo_price").notNull().default(0),
  targetMarginPercent: integer("target_margin_percent").notNull().default(40),
  staffInvolved: jsonb("staff_involved").notNull().default([]),
  disposableItems: jsonb("disposable_items").notNull().default([]),
  materialItems: jsonb("material_items").notNull().default([]),
  machineItems: jsonb("machine_items").notNull().default([]),
  commissionRules: jsonb("commission_rules").notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const products = pgTable("products", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  category: text("category").notNull().default(""),
  supplier: text("supplier").notNull().default(""),
  buyingTiers: jsonb("buying_tiers").notNull().default([]),
  normalPrice: integer("normal_price").notNull().default(0),
  vipPrice: integer("vip_price").notNull().default(0),
  promoPrice: integer("promo_price").notNull().default(0),
  stockQuantity: integer("stock_quantity"),
  commissionRules: jsonb("commission_rules").notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const simulationRecords = pgTable("simulation_records", {
  id: text("id").primaryKey(),
  itemType: text("item_type").notNull(),
  itemId: text("item_id").notNull(),
  itemName: text("item_name").notNull(),
  customerType: text("customer_type").notNull(),
  sellingPrice: integer("selling_price").notNull().default(0),
  quantity: integer("quantity").notNull().default(1),
  directHpp: integer("direct_hpp").notNull().default(0),
  overheadCost: integer("overhead_cost").notNull().default(0),
  totalCost: integer("total_cost").notNull().default(0),
  grossProfit: integer("gross_profit").notNull().default(0),
  totalCommission: integer("total_commission").notNull().default(0),
  netProfit: integer("net_profit").notNull().default(0),
  marginPercent: integer("margin_percent").notNull().default(0),
  commissionBreakdown: jsonb("commission_breakdown").notNull().default([]),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const commissionLogs = pgTable("commission_logs", {
  id: text("id").primaryKey(),
  date: text("date").notNull(),
  customerName: text("customer_name").notNull(),
  itemType: text("item_type").notNull(),
  itemId: text("item_id"),
  itemName: text("item_name").notNull(),
  customerType: text("customer_type").notNull(),
  sellingPrice: integer("selling_price").notNull().default(0),
  quantity: integer("quantity").notNull().default(1),
  staffName: text("staff_name").notNull().default(""),
  staffRole: text("staff_role").notNull().default("admin"),
  commissionAmount: integer("commission_amount").notNull().default(0),
  totalSales: integer("total_sales").notNull().default(0),
  totalHpp: integer("total_hpp").notNull().default(0),
  netProfit: integer("net_profit").notNull().default(0),
  paymentStatus: text("payment_status").notNull().default("unpaid"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
