import type { CommissionLog, ConsumableItem, FixedCostSettings, HppPackageTemplate, Product, SimulationRecord, Treatment } from "./types";

export const sampleFixedCosts: FixedCostSettings = {
  listrik: 4500000,
  air: 650000,
  internetTelepon: 950000,
  sewaTempat: 18000000,
  gajiDokter: 28000000,
  gajiTherapist: 16000000,
  gajiBeautician: 12000000,
  gajiAdmin: 7000000,
  bpjsTunjangan: 4500000,
  cleaningLaundry: 3000000,
  maintenanceAlat: 3500000,
  marketing: 8000000,
  softwareSubscription: 1250000,
  cicilanAlat: 12000000,
  cicilanRenovasi: 6500000,
  cicilanLain: 2500000,
  biayaTetapLain: 1750000,
  workingDays: 26,
  operatingHours: 9,
  averageCustomers: 420,
};

export const sampleTreatments: Treatment[] = [
  {
    id: "trt-glow-infusion",
    name: "Hera Glow Infusion",
    category: "Skin Booster",
    durationMinutes: 45,
    disposableCosts: [
      { id: "d1", name: "Needle / syringe", amount: 42000 },
      { id: "d2", name: "Gloves, mask, gauze", amount: 28000 },
      { id: "d3", name: "Alcohol swab", amount: 8000 },
      { id: "d4", name: "Cream / serum / gel", amount: 95000 },
      { id: "d5", name: "Consumable alat", amount: 35000 },
      { id: "d6", name: "Disposable lain", amount: 15000 },
    ],
    materialItems: [
      { id: "m1", name: "Skin booster vial", quantity: 1, unitCost: 360000 },
      { id: "m2", name: "Serum calming", quantity: 1, unitCost: 60000 },
    ],
    machineItems: [{ id: "mc1", name: "Injector device", amount: 85000, notes: "Alokasi alat per treatment" }],
    productMaterialCost: 420000,
    machineCostAllocation: 85000,
    staffInvolved: ["dokter", "therapist", "sales", "admin"],
    nonVipPrice: 1650000,
    vipPrice: 1450000,
    promoPrice: 1190000,
    targetMarginPercent: 45,
    commissionRules: [
      { id: "c1", role: "dokter", staffName: "dr. Anisa", quantity: 1, type: "sellingPercentage", value: 10, appliesTo: "All" },
      { id: "c2", role: "therapist", quantity: 1, type: "grossProfitPercentage", value: 7, appliesTo: "Normal" },
      { id: "c3", role: "beautician", quantity: 2, type: "fixed", value: 25000, appliesTo: "All" },
      { id: "c4", role: "sales", quantity: 1, type: "sellingPercentage", value: 3, appliesTo: "All" },
    ],
  },
  {
    id: "trt-laser-bright",
    name: "Hera Laser Bright",
    category: "Laser",
    durationMinutes: 35,
    disposableCosts: [
      { id: "d1", name: "Mask & gloves", amount: 22000 },
      { id: "d2", name: "Gauze & alcohol swab", amount: 12000 },
      { id: "d3", name: "Cooling gel", amount: 68000 },
      { id: "d4", name: "Consumable alat", amount: 55000 },
    ],
    materialItems: [{ id: "m1", name: "Cooling gel premium", quantity: 1, unitCost: 180000 }],
    machineItems: [{ id: "mc1", name: "Laser toning", amount: 210000, notes: "Shot allocation" }],
    productMaterialCost: 180000,
    machineCostAllocation: 210000,
    staffInvolved: ["dokter", "beautician", "admin"],
    nonVipPrice: 1250000,
    vipPrice: 1090000,
    promoPrice: 890000,
    targetMarginPercent: 42,
    commissionRules: [
      { id: "c1", role: "dokter", quantity: 1, type: "sellingPercentage", value: 5, appliesTo: "All" },
      { id: "c2", role: "beautician", quantity: 1, type: "fixed", value: 40000, appliesTo: "VIP" },
      { id: "c3", role: "admin", quantity: 1, type: "fixed", value: 20000, appliesTo: "Promo" },
    ],
  },
  {
    id: "trt-sculpt-facial",
    name: "Hera Sculpt Facial",
    category: "Facial Premium",
    durationMinutes: 75,
    disposableCosts: [
      { id: "d1", name: "Gloves & mask", amount: 20000 },
      { id: "d2", name: "Gauze", amount: 10000 },
      { id: "d3", name: "Cream / serum / gel", amount: 160000 },
      { id: "d4", name: "Disposable lain", amount: 25000 },
    ],
    materialItems: [
      { id: "m1", name: "Serum sculpt", quantity: 1, unitCost: 180000 },
      { id: "m2", name: "Mask premium", quantity: 1, unitCost: 80000 },
    ],
    machineItems: [{ id: "mc1", name: "RF facial device", amount: 120000 }],
    productMaterialCost: 260000,
    machineCostAllocation: 120000,
    staffInvolved: ["therapist", "beautician", "admin"],
    nonVipPrice: 950000,
    vipPrice: 825000,
    promoPrice: 690000,
    targetMarginPercent: 40,
    commissionRules: [
      { id: "c1", role: "therapist", quantity: 1, type: "fixed", value: 65000, appliesTo: "Normal" },
      { id: "c2", role: "beautician", quantity: 1, type: "fixed", value: 45000, appliesTo: "VIP" },
      { id: "c3", role: "therapist", quantity: 2, type: "grossProfitPercentage", value: 5, appliesTo: "Promo" },
    ],
  },
];

export const sampleProducts: Product[] = [
  {
    id: "prd-hera-hydra-serum",
    name: "Hera Hydra Serum",
    category: "Serum",
    supplier: "Hera Aesthetic Supply",
    buyingTiers: [
      { id: "t1", quantity: 1, unitCost: 185000 },
      { id: "t5", quantity: 5, unitCost: 165000 },
      { id: "t10", quantity: 10, unitCost: 145000 },
    ],
    selectedTierId: "t10",
    normalPrice: 365000,
    vipPrice: 325000,
    promoPrice: 289000,
    commissionRule: { id: "pc1", role: "beautician", quantity: 1, type: "sellingPercentage", value: 4 },
    commissionRules: [{ id: "pc1", role: "beautician", quantity: 1, type: "sellingPercentage", value: 4, appliesTo: "All" }],
    stockQuantity: 26,
  },
  {
    id: "prd-sunscreen",
    name: "Hera Velvet Sunscreen",
    category: "Sunscreen",
    supplier: "Derma Prime",
    buyingTiers: [
      { id: "t1", quantity: 1, unitCost: 92000 },
      { id: "t5", quantity: 5, unitCost: 84000 },
      { id: "t10", quantity: 10, unitCost: 78000 },
    ],
    selectedTierId: "t10",
    normalPrice: 195000,
    vipPrice: 175000,
    promoPrice: 149000,
    commissionRule: { id: "pc2", role: "admin", quantity: 1, type: "fixed", value: 10000 },
    commissionRules: [{ id: "pc2", role: "admin", quantity: 1, type: "fixed", value: 10000, appliesTo: "All" }],
    stockQuantity: 41,
  },
  {
    id: "prd-repair-cream",
    name: "Hera Barrier Repair Cream",
    category: "Moisturizer",
    supplier: "Skin Lab Indonesia",
    buyingTiers: [
      { id: "t1", quantity: 1, unitCost: 135000 },
      { id: "t5", quantity: 5, unitCost: 122000 },
      { id: "t10", quantity: 10, unitCost: 109000 },
    ],
    selectedTierId: "t5",
    normalPrice: 285000,
    vipPrice: 255000,
    promoPrice: 219000,
    commissionRule: { id: "pc3", role: "therapist", quantity: 1, type: "grossProfitPercentage", value: 8 },
    commissionRules: [{ id: "pc3", role: "therapist", quantity: 1, type: "grossProfitPercentage", value: 8, appliesTo: "All" }],
    stockQuantity: 18,
  },
];

export const sampleCommissionLogs: CommissionLog[] = [
  {
    id: "log-001",
    date: "2026-05-20",
    customerName: "Nadia Putri",
    itemName: "Hera Glow Infusion",
    itemType: "Treatment",
    customerType: "Non VIP",
    sellingPrice: 1650000,
    quantity: 1,
    staffName: "dr. Anisa",
    staffRole: "dokter",
    commissionAmount: 125000,
    netProfit: 418000,
    paymentStatus: "Belum dibayar",
    notes: "Paket single visit",
  },
  {
    id: "log-002",
    date: "2026-05-21",
    customerName: "Maya",
    itemName: "Hera Velvet Sunscreen",
    itemType: "Produk",
    customerType: "VIP",
    sellingPrice: 175000,
    quantity: 2,
    staffName: "Rani",
    staffRole: "admin",
    commissionAmount: 20000,
    netProfit: 174000,
    paymentStatus: "Sudah dibayar",
    notes: "Retail setelah facial",
  },
  {
    id: "log-003",
    date: "2026-05-22",
    customerName: "Clara",
    itemName: "Hera Laser Bright",
    itemType: "Treatment",
    customerType: "Promo",
    sellingPrice: 890000,
    quantity: 1,
    staffName: "Sinta",
    staffRole: "admin",
    commissionAmount: 20000,
    netProfit: 176000,
    paymentStatus: "Belum dibayar",
    notes: "Promo Mei",
  },
];

export const sampleSimulations: SimulationRecord[] = [];

export const sampleConsumables: ConsumableItem[] = [
  {
    id: "cons-kapas",
    name: "Kapas",
    category: "Disposable",
    supplier: "Hera Medical Supply",
    purchasePrice: 50000,
    purchaseQuantity: 1,
    purchaseUnit: "pack",
    totalSmallestUnit: 500,
    smallestUnit: "lembar",
    costPerSmallestUnit: 100,
    availableQuantity: 500,
    minimumStock: 100,
    notes: "1 pack isi 500 lembar",
  },
  {
    id: "cons-sabun-wajah",
    name: "Sabun wajah",
    category: "Cairan / Liquid",
    supplier: "Derma Prime",
    purchasePrice: 250000,
    purchaseQuantity: 1,
    purchaseUnit: "bottle",
    totalSmallestUnit: 1000,
    smallestUnit: "ml",
    costPerSmallestUnit: 250,
    availableQuantity: 1000,
    minimumStock: 200,
    notes: "1 liter = 1000 ml",
  },
  {
    id: "cons-alkohol-swab",
    name: "Alkohol swab",
    category: "Disposable",
    supplier: "Medika Sterile",
    purchasePrice: 80000,
    purchaseQuantity: 1,
    purchaseUnit: "box",
    totalSmallestUnit: 100,
    smallestUnit: "pcs",
    costPerSmallestUnit: 800,
    availableQuantity: 100,
    minimumStock: 20,
  },
  {
    id: "cons-gel-ultrasound",
    name: "Gel ultrasound",
    category: "Cairan / Liquid",
    supplier: "Beauty Device Care",
    purchasePrice: 120000,
    purchaseQuantity: 1,
    purchaseUnit: "bottle",
    totalSmallestUnit: 500,
    smallestUnit: "ml",
    costPerSmallestUnit: 240,
    availableQuantity: 500,
    minimumStock: 120,
  },
];

export const sampleHppPackages: HppPackageTemplate[] = [
  {
    id: "pkg-basic-facial",
    name: "Basic Facial Set",
    category: "Facial",
    description: "Set bahan standar untuk facial dasar.",
    totalCost: 4650,
    updatedAt: "2026-05-24",
    items: [
      { id: "pkgbf-1", mode: "master", consumableItemId: "cons-sabun-wajah", consumableName: "Sabun wajah", qtyDefault: 5, unit: "ml", costPerUnit: 250, totalCost: 1250 },
      { id: "pkgbf-2", mode: "manual", consumableName: "Sponge", manualName: "Sponge", qtyDefault: 2, unit: "pcs", costPerUnit: 1000, manualCost: 2000, totalCost: 2000 },
      { id: "pkgbf-3", mode: "manual", consumableName: "Toner", manualName: "Toner", qtyDefault: 3, unit: "ml", costPerUnit: 300, manualCost: 900, totalCost: 900 },
      { id: "pkgbf-4", mode: "master", consumableItemId: "cons-kapas", consumableName: "Kapas", qtyDefault: 5, unit: "lembar", costPerUnit: 100, totalCost: 500 },
    ],
  },
  {
    id: "pkg-meso-default",
    name: "Meso Default Set",
    category: "Meso / Booster",
    description: "Needle, syringe, antiseptik, gauze, numbing, dan booster.",
    totalCost: 104600,
    updatedAt: "2026-05-24",
    items: [
      { id: "pkgm-1", mode: "manual", consumableName: "Needle", manualName: "Needle", qtyDefault: 1, unit: "pcs", costPerUnit: 12000, manualCost: 12000, totalCost: 12000 },
      { id: "pkgm-2", mode: "manual", consumableName: "Syringe", manualName: "Syringe", qtyDefault: 1, unit: "syringe", costPerUnit: 15000, manualCost: 15000, totalCost: 15000 },
      { id: "pkgm-3", mode: "master", consumableItemId: "cons-alkohol-swab", consumableName: "Alkohol swab", qtyDefault: 2, unit: "pcs", costPerUnit: 800, totalCost: 1600 },
      { id: "pkgm-4", mode: "manual", consumableName: "Gauze", manualName: "Gauze", qtyDefault: 2, unit: "pcs", costPerUnit: 3000, manualCost: 6000, totalCost: 6000 },
      { id: "pkgm-5", mode: "manual", consumableName: "Numbing cream", manualName: "Numbing cream", qtyDefault: 2, unit: "gram", costPerUnit: 10000, manualCost: 20000, totalCost: 20000 },
      { id: "pkgm-6", mode: "manual", consumableName: "Serum meso / booster", manualName: "Serum meso / booster", qtyDefault: 1, unit: "vial", costPerUnit: 50000, manualCost: 50000, totalCost: 50000 },
    ],
  },
  {
    id: "pkg-laser-prep",
    name: "Laser Preparation Set",
    category: "Laser / Energy Based Device",
    description: "Persiapan kulit sebelum laser atau EBD.",
    totalCost: 4420,
    updatedAt: "2026-05-24",
    items: [
      { id: "pkgl-1", mode: "master", consumableItemId: "cons-sabun-wajah", consumableName: "Sabun wajah", qtyDefault: 4, unit: "ml", costPerUnit: 250, totalCost: 1000 },
      { id: "pkgl-2", mode: "master", consumableItemId: "cons-kapas", consumableName: "Kapas", qtyDefault: 6, unit: "lembar", costPerUnit: 100, totalCost: 600 },
      { id: "pkgl-3", mode: "master", consumableItemId: "cons-alkohol-swab", consumableName: "Alkohol swab", qtyDefault: 1, unit: "pcs", costPerUnit: 800, totalCost: 800 },
      { id: "pkgl-4", mode: "master", consumableItemId: "cons-gel-ultrasound", consumableName: "Gel ultrasound", qtyDefault: 8, unit: "ml", costPerUnit: 240, totalCost: 1920 },
      { id: "pkgl-5", mode: "manual", consumableName: "Disposable head cover", manualName: "Disposable head cover", qtyDefault: 1, unit: "pcs", costPerUnit: 100, manualCost: 100, totalCost: 100 },
    ],
  },
];
